on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      env:
        NODE_VERSION: [14.x, 16.x]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: install, build, and test (unit and e2e)
        run: |
          npm install
          npm build --if-present
          npm test --if-present
